### ISSUE TITLE
ArgumentError (Unsupported adapter: sqlite3)

### ISSUE THREAD

**Issue by kirantpatil** [tombenner/reports_kit#21]
Hi,

I added https://www.reportskit.co/subcategories/quick_start code and I am getting below error and UI is not showing anything but loading icon as below.

## Setup
Ruby 2.4.1
Rails 5.0.1
Sqlite
Ubuntu

## Error

```
puma (3.6.2) lib/puma/server.rb:275:in `block in run'
puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered collection of /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb [796 times] (210.0ms)
  Rendered collection of /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb [2 times] (0.8ms)
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.4ms)
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (303.1ms)
Started GET "/reports_kit/reports.json?report_params%5Bkey%5D=data_overview&properties=%7B%22ui_filters%22%3A%7B%7D%7D" for 127.0.0.1 at 2017-12-12 13:29:17 +0530
Processing by ReportsKit::ReportsController#index as JSON
  Parameters: {"report_params"=>{"key"=>"data_overview"}, "properties"=>"{\"ui_filters\":{}}"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

ArgumentError (Unsupported adapter: sqlite3):
  
reports_kit (0.5.0) lib/reports_kit/reports/dimension_with_series.rb:118:in `adapter'
reports_kit (0.5.0) lib/reports_kit/reports/dimension_with_series.rb:132:in `week_expression'

```

## Screenshot
![screenshot-2017-12-12 hocc](https://user-images.githubusercontent.com/1178055/33873598-9f3189b4-df41-11e7-93ad-818fb3dc2a1f.png)

**Comment by kirantpatil** [comment]
I changed database to Postgresql and now it works but having css issue which I updated at https://github.com/tombenner/reports_kit/issues/20

**Comment by nynhex** [comment]
@kirantpatil This seems to only work with Postgres/MySQL I could not get it to work with sqlite3
